/**
 * Action Constants Module
 * 
 * Contains constants used by the actions functionality.
 */

// List of available action base words.
export const actionTags = [
    "dancing",
    "fighting",
    "kissing",
    "flirting",
    "mutual tail biting",
    "cooperative grinding",
    "spooning",
    "pointing",
    "kicking",
    "slapping",
    "pushing",
    "cuddling",
    "cupping",
    "headpat",
    "groping",
    "tail fondling",
    "rubbing",
    "biting ass",
    "biting another's tail",
    "breast biting",
    "biting cheek",
    "biting ear",
    "biting finger",
    "biting foreskin",
    "biting glove",
    "biting another's hand",
    "biting head",
    "biting penis",
    "elbowing",
    "hitting",
    "punching",
    "pulling",
    "throwing",
    "fingering",
    "anal fingering",
    "fisting",
    "anal fisting",
    "licking armpit",
    "licking breast",
    "licking another's cheek",
    "licking cum",
    "licking ear",
    "licking eye",
    "licking another's face",
    "licking finger",
    "licking floor",
    "licking foot",
    "licking blade",
    "licking leg",
    "licking navel",
    "licking nipple",
    "licking panties",
    "licking testicle",
    "licking thigh",
    "breast sucking",
    "finger sucking",
    "toe sucking",
    "unzipping with mouth",
    "unzipping",
    "dry humping",
    "humping",
    "spanking",
    "squirting liquid",
    "apologizing",
    "beckoning",
    "begging",
    "comforting",
    "feeding",
    "pov feeding",
    "patting",
    "pinching",
    "cheek pinching",
    "tickling",
    "tickling feet",
    "forced dressing",
    "undressing",
    "ear cleaning",
    "drawing on another's face",
    "measuring bust",
    "measuring penis",
    "measuring waist",
    "pantsing",
    "aiming",
    "aiming at viewer"
]; 